---
- hosts: all
  become: true
  tasks:
    - name: Update and install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted